server/server/urls.py
from django.contrib import admin
from django.urls import path
from searchfile.views import home
from django.conf.urls import url
from NutriliteSearchPage.views import NutriliteSearchPage,viewFilePage,returnPDF,exchangeOption,keywordSearchPage,returnFileStatus
from django .contrib.auth.decorators import login_required
from userlogin.views import login,logout,register,createRegisterPage,checkRegDD,registerSuccess,\
    forgetPasswordGetMail,forgetPasswordModify,forgetPasswordKeyinNumber,forgetPasswordConfirmPage
from personalInfoPage.views import personalInfoHomePage, personalInfoPointPage,changePasswordPage,changePasswordOption
from managerPage.views import managerAccountManagerPage,managerAuditAccountPage,removeAuditAccount,AcceptAuditAccount
from managerPage.views import userAccountConfirm,managerAccountModify,modalAccountModifyPOST
from managerPage.views import managerPointManagerPage, getAccountModifyHistory, managerArticleManagerPage, \
    managerStatisticManagerPage, managerArticleReportManagerPage, managerRewardReportManagerPage, \
    managerBlackListManagerPage
from django.conf.urls import url
from addlikes.views import like_change,putStars
from recommendIndex.views import recommendIndexHome

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.views.generic.base import RedirectView

urlpatterns+=[
    url(r'^home', login_required(home)),
    # url("/", login_required(home)),
    # url(r'^home/NutriliteSearchPage/<str:selectTag>', NutriliteSearchPage),
]


urlpatterns += [
    path('home', login_required(home), name='home'),
    path('accounts/login/', login, name='login'),
    path('accounts/logout/', logout, name='logout'),
    path('accounts/registerSuccessStatus/<str:status>', registerSuccess, name='registerSuccess'),
    path('accounts/register/<str:token>', register,name='register'),
    path('accounts/createRegisterPage/', createRegisterPage,name='createRegisterPage'),
    path('accounts/forgetPassword/GetMail', forgetPasswordGetMail,name='forgetPasswordGetMail'),
    path('accounts/forgetPassword/modify', forgetPasswordModify,name='forgetPasswordModify'),
    path('accounts/forgetPassword/confirmPage', forgetPasswordConfirmPage,name='forgetPasswordConfirmPage'),
    path('accounts/forgetPassword/keyinPage', forgetPasswordKeyinNumber,name='forgetPasswordKeyinNumber'),


    path('filesearch/<str:topic>/<str:selectTag>', login_required(NutriliteSearchPage), name='NutriliteSearchPage'),

    path('viewFilePage/<str:fileId>', login_required(viewFilePage), name='viewFilePage'),
    path('keywordSearchPage', login_required(keywordSearchPage), name='keywordSearchPage'),

    path('returnPDF/<str:fileId>', login_required(returnPDF), name='returnPDF'),
    path('returnFileStatus/<str:fileId>', login_required(returnFileStatus), name='returnFileStatus'),
    path('exchangeOption/<str:fileId>', login_required(exchangeOption), name='exchangeOption'),
    path('personalInfoPage/home/<str:selectTag>', login_required(personalInfoHomePage), name='personalInfoHomePage'),
    path('personalInfoPage/pointPage', login_required(personalInfoPointPage), name='personalInfoPointPage'),
    path('personalInfoPage/changePasswordPage', login_required(changePasswordPage), name='changePasswordPage'),
    path('personalInfoPage/changePasswordOption', login_required(changePasswordOption), name='changePasswordOption'),

    path('managerPages/home/accountManger', login_required(managerAccountManagerPage), name='managerAccountManagerPage'),
    path('managerPages/home/blackList', login_required(managerBlackListManagerPage), name='managerBlackListManagerPage'),
    path('managerPages/home/AuditManger', login_required(managerAuditAccountPage),name='managerAuditAccountPage'),
    path('managerPages/home/PointManager', login_required(managerPointManagerPage),name='managerPointManagerPage'),
    path('managerPages/home/ArticleManager', login_required(managerArticleManagerPage),name='managerArticleManagerPage'),
    path('managerPages/home/ArticleReportManager', login_required(managerArticleReportManagerPage),name='managerArticleReportManagerPage'),
    path('managerPages/home/RewardReportManager', login_required(managerRewardReportManagerPage),name='managerRewardReportManagerPage'),
    path('managerPages/home/StatisticManager', login_required(managerStatisticManagerPage),name='managerStatisticManagerPage'),
    path('managerPages/removeAuditAccount', login_required(removeAuditAccount),name='removeAuditAccount'),
    path('managerPages/AcceptAuditAccount', login_required(AcceptAuditAccount),name='AcceptAuditAccount'),
    path('managerPages/userAccountConfirm', userAccountConfirm,name='userAccountConfirm'),
    path('managerPages/managerAccountModify',managerAccountModify,name='managerAccountModify'),
    path('managerPages/modalAccountModifyPOST',modalAccountModifyPOST,name='modalAccountModifyPOST'),
    path('managerPages/getAccountModifyHistory',getAccountModifyHistory,name='getAccountModifyHistory'),
    path('like_change',like_change,name='like_change'),
    path('putStars',putStars,name='putStars'),
    path('checkRegDD', checkRegDD, name='checkRegDD'),

    # 推薦索引
    path('recommendIndexHome', recommendIndexHome, name='recommendIndexHome'),
    path('', login_required(home), name='home'),
]

# Use include() to add paths from the catalog application
from django.conf.urls import include

urlpatterns += [
    path('pointManage/', include('pointManage.urls')),
    path('managerPages/', include('managerPage.urls')),
    path('personalInfoPage/', include('personalInfoPage.urls')),
    path('courseReplay/', include('courseReplay.urls')),
]

server/NutriliteSearchPage/models.py
from django.db import models
from django.utils import timezone


class fileDataInfo(models.Model):
    title = models.CharField(max_length=50, verbose_name='標題')
    mainClass = models.ForeignKey("mainClassInfo",verbose_name='主類別',on_delete=models.PROTECT)
    secClass = models.ForeignKey("secClassInfo",verbose_name = '次類別',on_delete=models.PROTECT)
    describe = models.CharField(max_length=500, verbose_name='描述')
    PDF = models.CharField(max_length=255,verbose_name='PDF路徑',null=True,blank=True)
    file = models.CharField(max_length=255,verbose_name='file路徑')
    fileType = models.ForeignKey("fileTypeInfo",verbose_name='檔案格式',on_delete=models.PROTECT)
    sourceFrom = models.ForeignKey("sourceFromInfo",verbose_name='資料來源',on_delete=models.PROTECT)
    sourceURL = models.CharField(max_length=255,verbose_name='來源網址',null=True,blank=True)
    sourceScreenshot = models.CharField(max_length=255,verbose_name='來源示意圖路徑',null=True,blank=True)
    characterName = models.CharField(max_length=20,verbose_name='421主角姓名',null=True,blank=True)
    characterClass = models.ForeignKey("userlogin.chainYenClassInfo",verbose_name='421主角歸屬教室',null=True,blank=True,on_delete=models.PROTECT)
    characterDD = models.CharField(max_length=20,verbose_name='421主角上手白金',null=True,blank=True)
    occurrenceDate = models.DateTimeField(verbose_name='資料發生日期')
    lastModify = models.DateTimeField(verbose_name='資料修改日期')
    visible = models.BooleanField(verbose_name='是否可見')
    needWaterMark = models.BooleanField(verbose_name='是否需要浮水印')
    point = models.IntegerField(verbose_name='耗費點數')
    permissionsLevel = models.IntegerField(verbose_name='權限等級')
    DBClass = models.ForeignKey("DBClassInfo",verbose_name='資料庫類別',on_delete=models.PROTECT)
    downloadAble = models.BooleanField(verbose_name='是否可以下載')
    likes = models.IntegerField(default=0,verbose_name="按讚數")
    stars = models.FloatField(default=0, verbose_name="星星平均")
    exchangeCount = models.IntegerField(default=0,verbose_name="被兌換的次數")

    class Meta:
        verbose_name = "檔案管理"
        verbose_name_plural = "檔案管理"

    def __str__(self):
        return self.title

#資料庫類別對應表
class DBClassInfo(models.Model):

    DBClassName = models.CharField(max_length=100,verbose_name='名稱')
    DBClassCode = models.CharField(max_length=50,verbose_name='編碼')
    def __str__(self):
        return self.DBClassCode

    class Meta:
        verbose_name = "資料庫類別對應表(C.A.O)"
        verbose_name_plural = "資料庫類別對應表(C.A.O)"

#主類別對應表
class mainClassInfo(models.Model):

    mainClassName = models.CharField(max_length=50,verbose_name='主類別名稱',null=True,blank=True)
    def __str__(self):
        return self.mainClassName
    class Meta:
        verbose_name = "主類別對應表"
        verbose_name_plural = "主類別對應表"

#次類別對應表
class secClassInfo(models.Model):
    secClassName = models.CharField(max_length=50, verbose_name='主類別名稱', null=True,blank=True)
    def __str__(self):
        return self.secClassName
    class Meta:
        verbose_name = "次類別對應表"
        verbose_name_plural = "次類別對應表"

#檔案類型對應表
class fileTypeInfo(models.Model):

    fileTypeName = models.CharField(max_length=50,verbose_name='檔案類型對應表',null=True,blank=True)
    def __str__(self):
        return self.fileTypeName
    class Meta:
        verbose_name = "檔案類型對應表"
        verbose_name_plural = "檔案類型對應表"
        
#資料來源對應表
class sourceFromInfo(models.Model):
    sourceFromName = models.CharField(max_length=50, verbose_name='資料來源名稱', null=True,blank=True)
    def __str__(self):
        return self.sourceFromName
    class Meta:
        verbose_name = "資料來源對應表"
        verbose_name_plural = "資料來源對應表"

class fileDataKeywords(models.Model):
    fileDataInfoID = models.ForeignKey('fileDataInfo',verbose_name='對應的資料ID',on_delete=models.CASCADE)
    keyword = models.CharField(max_length=40, verbose_name='關鍵字名稱', null=True,blank=True)
    class Meta:
        verbose_name = "檔案關鍵字"
        verbose_name_plural = "檔案關鍵字"

#個人持有資料
class personalFileData(models.Model):
    fileDataID = models.ForeignKey('fileDataInfo',on_delete=models.CASCADE,verbose_name='對應的資料')
    ownerAccount = models.ForeignKey('userlogin.UserAccountInfo',on_delete=models.CASCADE,verbose_name='對應的帳號')
    exchangeDate = models.DateTimeField(verbose_name='資料兌換日期')
    expiryDate = models.DateField(verbose_name='資料兌換時效到期日',null=True,blank=True)
    create_Date_S = models.DateTimeField(verbose_name='轉檔開始時間', null=True, blank=True,default=timezone.now)
    create_Date_E = models.DateTimeField(verbose_name='轉檔結束時間', null=True, blank=True,default=timezone.now)
    costPoint = models.IntegerField(verbose_name='花費點數')
    waterCreateReady = models.BooleanField(default=0,verbose_name='浮水印是否完成')
    waterMarkPath = models.CharField(max_length=400,verbose_name='浮水印檔案路徑', null=True,blank=True)
    like = models.BooleanField(default=0,verbose_name='是否按讚')
    stars = models.FloatField(default=0,verbose_name='星級評分')
    getStar = models.BooleanField(default=0, verbose_name='是否給評分')
    class Meta:
        verbose_name = "個人持有資料管理"
        verbose_name_plural = "個人持有資料管理"

class personalExchangeFileLog(models.Model):
    fileDataID = models.ForeignKey('fileDataInfo', on_delete=models.CASCADE, verbose_name='對應的資料')
    ownerAccount = models.ForeignKey('userlogin.UserAccountInfo', on_delete=models.CASCADE, verbose_name='對應的帳號')
    exchangeDate = models.DateTimeField(verbose_name='資料兌換日期',default=timezone.now)
    costPoint = models.IntegerField(verbose_name='花費點數')
    class Meta:
        verbose_name = "個人兌換紀錄"
        verbose_name_plural = "個人兌換紀錄"

#瀏覽紀錄
class personalWatchFileLog(models.Model):
    fileDataID = models.ForeignKey('fileDataInfo', on_delete=models.CASCADE, verbose_name='對應的資料')
    watchAccount = models.ForeignKey('userlogin.UserAccountInfo', on_delete=models.CASCADE, verbose_name='對應的帳號')
    exchangeDate = models.DateTimeField(verbose_name='瀏覽時間',default=timezone.now)
    class Meta:
        verbose_name = "個人觀看紀錄"
        verbose_name_plural = "個人觀看紀錄"

class articleModifyHistory(models.Model):
    fileDataID = models.ForeignKey('fileDataInfo', on_delete=models.CASCADE, verbose_name='對應的資料')
    modifier  = models.CharField(max_length=50, verbose_name='修改者')
    title     = models.CharField(max_length=50, verbose_name='標題')
    mainClass = models.ForeignKey("mainClassInfo", verbose_name='主類別', on_delete=models.PROTECT)
    secClass  = models.ForeignKey("secClassInfo", verbose_name = '次類別', on_delete=models.PROTECT)
    keyword   = models.CharField(max_length=500, verbose_name='關鍵字')
    describe  = models.CharField(max_length=500, verbose_name='描述')
    point     = models.IntegerField(verbose_name='耗費點數')
    visible   = models.BooleanField(verbose_name='是否可見')
    recordDate = models.DateTimeField(verbose_name='修改日期')

class articleReport(models.Model):
    fileData      = models.ForeignKey('fileDataInfo', on_delete=models.CASCADE, verbose_name='對應的資料')
    reporter      = models.ForeignKey('userlogin.UserAccountInfo', related_name="reporter", on_delete=models.CASCADE, verbose_name='回報者')
    handler       = models.ForeignKey('userlogin.UserAccountInfo', related_name="handler", on_delete=models.CASCADE, verbose_name='處理者', null=True)
    reason        = models.CharField(max_length=50, verbose_name='回報原因')
    status        = models.CharField(max_length=50, verbose_name='狀態') #待處理report/已完成finish/無效回報discard
    discardReason = models.CharField(max_length=50, verbose_name='無效原因', null= True)
    recordDate    = models.DateTimeField(verbose_name='回報日期')
    handleDate      = models.DateTimeField(verbose_name='處理日期', null=True)

server/templates/MainSearchPage.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>

<head>
	<title>ChainYen System</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

	<link href="{%static 'favicon.ico' %}" rel="shortcut icon">
	<style type="text/css">

		a{
			color:black;
		}
		.classNoActivate {
			background-color: white;
			color: black;
		}
		.list-inline {
			display: block;
		}

		.list-inline li {
			display: inline-block;
		}

		.list-inline li:after {
			content: '|';
			margin: 0 10px;
			color:white;
		}
	</style>

</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Header -->
		{% include 'baseHeader.html' %}

		<!-- Menu -->
		{% include 'baseMenu.html' %}

		<!-- Banner -->
		{% include 'searchbar.html' %}
		<!-- Note: The "styleN" class below should match that of the header element. -->

		<!-- Main -->
		<div id="main">
			<section id=""
				style="background-image:url('{%static 'images/標題底圖.png'  %}'); background-size: cover; background-repeat: no-repeat; ">

				{% if topic == "營養" %}
				{% include 'searchPagesHeader/nutSearchPageHead.html' %}
				{% elif topic == "美容" %}
				{% include 'searchPagesHeader/artistrySearchPageHead.html' %}
				{%elif topic == "科技" %}
				{% include 'searchPagesHeader/TechSearchPageHead.html' %}
				{%elif topic == "金鍋" %}
				{% include 'searchPagesHeader/QueenSearchPageHead.html' %}
				{%elif topic == "其他" %}
				{% include 'searchPagesHeader/othersSearchPageHead.html' %}
				{%elif topic == "演講廳" %}
				{% include 'searchPagesHeader/courseSearchPageHead.html' %}
				{%elif topic == "總部會議/活動" %}
				{% include 'searchPagesHeader/meetingSearchPageHead.html' %}
				{% endif %}
			</section>
			<section id="two" class="spotlights"
				style="background-size: Cover;background:url('{%static 'images/login底圖.png' %}');">

				<div class="inner">
					{% for fileData in fileDatas%}

					<!--									style="background-color:rgb(231,209,179);">-->
					<div style=" border-bottom: 1px solid black;">
						<h3 style="margin-bottom: 0px">
						{% if fileData.id in ownFileList %}
						<b style="color:#117a8b">{{fileData.title}}</b>
						{% else %}
						<b>{{fileData.title}}</b>
						{% endif %}
						{% if fileData.fileType.id == 1 %}
						<img src="{% static 'images/video.png' %}" width="20px" heigh="20px"></h3>
						{% else %}
						<img src="{% static 'images/pdf.png' %}" width="20px" heigh="20px"></h3>
						{% endif %}
						<details style="margin-bottom: 30px;color:#CE0000">
							<summary>查看更多...</summary>
							<p>{{fileData.describe}}</p>
								<ul class="list-inline">
								{% for keywords in fileData.filedatakeywords_set.all %}
									<li>

										<a style="background-color: transparent;" class="classNoActivate" href="/keywordSearchPage?keywords={{keywords.keyword}}&timelim=100" class="" >#{{keywords.keyword}}</a>

									</li>
								{% endfor %}
								</ul>
<!--							<div class="like">-->
<!--								<span class="glyphicon glyphicon-thumbs-up"></span>-->
<!--								<span class="liked-num">{{fileData.likes}}</span>-->
<!--							</div>-->
							<h3 style="color:black"><img src="{% static 'images/star.png' %}" width="20px" heigh="20px">{{fileData.stars|stringformat:".1f"}}</h3>
							<ul class="actions">
								<li>

									{% if fileData.id in ownFileList %}
									<button type="button" class="button"
										onclick="searPageViewFileSubmit({{ fileData.id }})">
										點選觀看
									</button>

									{% elif userpoint >= fileData.point %}
									<button type="button" class="button" data-toggle="modal"
										data-target="#confirmViewFile"
										onclick="confirmViewFile({{ fileData.id }},'{{fileData.title}}',{{fileData.point}},{{userpoint}})">
										兌換觀看【{{fileData.point}}點】
									</button>
									{% else %}
									<button type="button" class="button" data-toggle="modal"
										data-target="#confirmViewFile" disabled>
										兌換觀看【{{fileData.point}}點】
									</button>
									{% endif %}
								</li>
							</ul>
						</details>
					</div>
					{% endfor %}
					{% if pageisNotNull is False %}
					<div style="height:40vh; ">
						<p>沒有資料...</p>
					</div>
					{% endif %}
					{% if pageisNotNull %}
					<br>
					<div class="dataTables_paginate paging_simple_numbers pull-right inner">
						<ul class="pagination ">
							{{ pagination.page_html|safe }}
						</ul>

					</div>
					{% endif %}

				</div>


			</section>


		</div>


	</div>

	<!-- Modal -->
	<div class="modal fade" id="confirmViewFile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
		aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h3 style="color: black" class="modal-title" id="fileCheckTitle"></h3>
				</div>
				<div class="modal-body" id="modal-boyd">
					<p style="color: black" id="userpoint"></p>
					<label style="color: red" for="demo-copy">*兌換即同意不截圖、不錄音、不錄影、不外流</label>
				</div>
				<div class="modal-footer">
					<form action="22" id="fileIDModal" name="fileIDModal" method="post">{% csrf_token %}
						<input type="hidden" id="fileViewID">
					</form>>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
					<button type="button" class="btn btn-primary" onclick="confirmViewFileSubmit()">我同意並兌換</button>
				</div>
			</div>
		</div>
	</div>


	<!-- Scripts -->

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
		crossorigin="anonymous"></script>
	
	<style type="text/css">
		.list-inline {
			display: block;
		}

		.list-inline li {
			display: inline-block;
		}

		.list-inline li:after {
			content: '|';
			margin: 0 10px;
		}

		.searchBar-inline {
			display: block;
		}

		.searchBar-inline li {
			display: inline-block;
		}

		p {
			color: black;
		}

		b {
			color: black;
		}

		.button {
			border: 1px solid black;
			color: black;
		}

		.page {
			color: black;
			background-color: transparent;
		}

		.classActivate {
			background-color: black;
			color: white;
		}

		.classNoActivate {
			background-color: white;
			color: black;
		}

		#keywords::-webkit-input-placeholder {
			color: rgba(255, 255, 255, 0.4) !important;
			opacity: 1.0;
		}

		#keywords:-moz-placeholder {
			color: rgba(255, 255, 255, 0.2) !important;
			opacity: 1.0;
		}

		#keywords::-moz-placeholder {
			color: rgba(255, 255, 255, 0.2) !important;
			opacity: 1.0;
		}

		#keywords:-ms-input-placeholder {
			color: rgba(255, 255, 255, 0.2) !important;
			opacity: 1.0;
		}

		div.like {
			color: #337ab7;
			cursor: pointer;
			display: inline-block;
			padding: 0.5em 0.3em;
		}

		@font-face {
			font-family: 'Glyphicons Halflings';
			src: url('https://netdna.bootstrapcdn.com/bootstrap/3.0.0/fonts/glyphicons-halflings-regular.eot');
			src: url('https://netdna.bootstrapcdn.com/bootstrap/3.0.0/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('https://netdna.bootstrapcdn.com/bootstrap/3.0.0/fonts/glyphicons-halflings-regular.woff') format('woff'), url('https://netdna.bootstrapcdn.com/bootstrap/3.0.0/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('https://netdna.bootstrapcdn.com/bootstrap/3.0.0/fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg');
		}

		.glyphicon {
			position: relative;
			top: 1px;
			display: inline-block;
			font-family: 'Glyphicons Halflings';
			font-style: normal;
			font-weight: normal;
			line-height: 1;
			-webkit-font-smoothing: antialiased;
		}

		.glyphicon-thumbs-up:before {
			content: "\e125";
		}
	</style>
</body>

</html>

server/templates/viewFilePageCantDownload.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<html>
<head>
	<title>ChainYen System</title>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>

	{% load static %}
	<link href="{%static 'favicon.ico' %}" rel="shortcut icon">
</head>
	<body class="is-preload" style="background-size: Cover;background:url('{%static 'images/login底圖.png' %}');">

		<!-- Wrapper -->
			<div id="wrapper" class="container" >

				<!-- Header -->
					{% include 'baseHeader.html' %}

				<!-- Menu -->
					{% include 'baseMenu.html' %}

				<!-- Main -->
				{% if permission is False %}
				<p>權限不足</p>
				{% elif pointEnough is False %}
				<p>點數不足</p>
				{% else %}
					<div id="main" class="alt">

						<!-- One -->
							<section id="one">
								<div class="inner">
									<header class="">
										<h3><b>{{targetFile.title}}</b></h3>
									</header>
									<p>{{targetFile.describe}}</p>
									<input type="hidden" id="fileID" value = "{{targetFile.id}}">
									<p>關鍵字:
										{% for keywords in targetFile.filedatakeywords_set.all %}
												#{{keywords.keyword}}
										{% endfor %}
									</p>
									{% if alreadyExchange is False %}
									<ul class="actions">
										<li>

											{% if UserAccountChainYen.point >= targetFile.point %}
											<button type="button" class="button" data-toggle="modal"
													data-target="#confirmViewFile"
													onclick="confirmViewFile({{ targetFile.id }},'{{targetFile.title}}',{{ targetFile.point }},{{UserAccountChainYen.point}})">
												兌換觀看【{{targetFile.point}}點】
											</button>
											{% else %}
											<button type="button" class="button" data-toggle="modal"
													data-target="#confirmViewFile" disabled>
												兌換觀看【{{targetFile.point}}點】
											</button>
											{% endif %}
										</li>
									</ul>


									{% endif %}
									{% if alreadyExchange %}
                                    <p>google 雲端的ID為:</p>
                                    <p>{{targetFile.PDF}}</p>
                                    <p>下載請洽詢總部</p>
									{% endif %}
								</div>

							</section>

					</div>

				{% endif %}

			</div>
		{% if alreadyExchange %}

		{% else %}

		<div class="modal fade" id="confirmViewFile" tabindex="-1" role="dialog"
			 aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h3 style="color: black" class="modal-title"
							id="fileCheckTitle"></h3>
<!--						<h3 style="color: black" class="modal-title" id="needPoint"></h3>-->
						<button type="button" class="close" data-dismiss="modal"
								aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body" id="modal-boyd">
						<p style="color: black" id="userpoint"></p>
						<label style="color: red"
							   for="demo-copy">*兌換即同意不截圖、不錄音、不錄影、不外流</label>
					</div>
					<div class="modal-footer">
						<form action="22" id="fileIDModal" name="fileIDModal" method="post">
							{% csrf_token %}
							<input type="hidden" id="fileViewID">
						</form>

						<button type="button" class="btn btn-secondary"
								data-dismiss="modal">取消
						</button>
						<button type="button" class="btn btn-primary"
								onclick="confirmViewFileSubmit()">我同意並兌換
						</button>
					</div>
				</div>
			</div>
		</div>
		{% endif %}


		<!-- Scripts -->
			<script type="text/javascript" src="{%static 'assets/js/pdfobject.min.js'%}"></script>
			<script type="text/javascript" src="{%static 'pdfjs-2.0/build/pdf.js'%}"></script>
			<style type="text/css">
				html, body, #pdf_viewer {
					width: 100%;
					height: 100%;
					margin: 0;
					padding: 0;
				}
				#myProgress {
					position: relative;
					width: 100%;
					height: 30px;
					background-color: #ddd;
				}
		
				#myBar {
					position: absolute;
					width: 1%;
					height: 100%;
					background-color: #4CAF50;
				}
				p {color:black;}
				b {color:black;}
				.button {
					border: 1px solid black;
					color:black;
				}
			</style>


	</body>
</html>