server/personalInfoPage/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('personalRewardReport', views.personalRewardReport, name='personalRewardReport'),
    path('getSelfRewardReport', views.getSelfRewardReport, name='getSelfRewardReport'),
    path('rewardReportByExcel', views.rewardReportByExcel, name='rewardReportByExcel'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path
from searchfile.views import home
from django.conf.urls import url
from NutriliteSearchPage.views import NutriliteSearchPage,viewFilePage,returnPDF,exchangeOption,keywordSearchPage,returnFileStatus
from django .contrib.auth.decorators import login_required
from userlogin.views import login,logout,register,createRegisterPage,checkRegDD,registerSuccess,\
    forgetPasswordGetMail,forgetPasswordModify,forgetPasswordKeyinNumber,forgetPasswordConfirmPage
from personalInfoPage.views import personalInfoHomePage, personalInfoPointPage,changePasswordPage,changePasswordOption
from managerPage.views import managerAccountManagerPage,managerAuditAccountPage,removeAuditAccount,AcceptAuditAccount
from managerPage.views import userAccountConfirm,managerAccountModify,modalAccountModifyPOST
from managerPage.views import managerPointManagerPage, getAccountModifyHistory, managerArticleManagerPage, \
    managerStatisticManagerPage, managerArticleReportManagerPage, managerRewardReportManagerPage, \
    managerBlackListManagerPage
from django.conf.urls import url
from addlikes.views import like_change,putStars
from recommendIndex.views import recommendIndexHome

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.views.generic.base import RedirectView

urlpatterns+=[
    url(r'^home', login_required(home)),
    # url("/", login_required(home)),
    # url(r'^home/NutriliteSearchPage/<str:selectTag>', NutriliteSearchPage),
]


urlpatterns += [
    path('home', login_required(home), name='home'),
    path('accounts/login/', login, name='login'),
    path('accounts/logout/', logout, name='logout'),
    path('accounts/registerSuccessStatus/<str:status>', registerSuccess, name='registerSuccess'),
    path('accounts/register/<str:token>', register,name='register'),
    path('accounts/createRegisterPage/', createRegisterPage,name='createRegisterPage'),
    path('accounts/forgetPassword/GetMail', forgetPasswordGetMail,name='forgetPasswordGetMail'),
    path('accounts/forgetPassword/modify', forgetPasswordModify,name='forgetPasswordModify'),
    path('accounts/forgetPassword/confirmPage', forgetPasswordConfirmPage,name='forgetPasswordConfirmPage'),
    path('accounts/forgetPassword/keyinPage', forgetPasswordKeyinNumber,name='forgetPasswordKeyinNumber'),


    path('filesearch/<str:topic>/<str:selectTag>', login_required(NutriliteSearchPage), name='NutriliteSearchPage'),

    path('viewFilePage/<str:fileId>', login_required(viewFilePage), name='viewFilePage'),
    path('keywordSearchPage', login_required(keywordSearchPage), name='keywordSearchPage'),

    path('returnPDF/<str:fileId>', login_required(returnPDF), name='returnPDF'),
    path('returnFileStatus/<str:fileId>', login_required(returnFileStatus), name='returnFileStatus'),
    path('exchangeOption/<str:fileId>', login_required(exchangeOption), name='exchangeOption'),
    path('personalInfoPage/home/<str:selectTag>', login_required(personalInfoHomePage), name='personalInfoHomePage'),
    path('personalInfoPage/pointPage', login_required(personalInfoPointPage), name='personalInfoPointPage'),
    path('personalInfoPage/changePasswordPage', login_required(changePasswordPage), name='changePasswordPage'),
    path('personalInfoPage/changePasswordOption', login_required(changePasswordOption), name='changePasswordOption'),

    path('managerPages/home/accountManger', login_required(managerAccountManagerPage), name='managerAccountManagerPage'),
    path('managerPages/home/blackList', login_required(managerBlackListManagerPage), name='managerBlackListManagerPage'),
    path('managerPages/home/AuditManger', login_required(managerAuditAccountPage),name='managerAuditAccountPage'),
    path('managerPages/home/PointManager', login_required(managerPointManagerPage),name='managerPointManagerPage'),
    path('managerPages/home/ArticleManager', login_required(managerArticleManagerPage),name='managerArticleManagerPage'),
    path('managerPages/home/ArticleReportManager', login_required(managerArticleReportManagerPage),name='managerArticleReportManagerPage'),
    path('managerPages/home/RewardReportManager', login_required(managerRewardReportManagerPage),name='managerRewardReportManagerPage'),
    path('managerPages/home/StatisticManager', login_required(managerStatisticManagerPage),name='managerStatisticManagerPage'),
    path('managerPages/removeAuditAccount', login_required(removeAuditAccount),name='removeAuditAccount'),
    path('managerPages/AcceptAuditAccount', login_required(AcceptAuditAccount),name='AcceptAuditAccount'),
    path('managerPages/userAccountConfirm', userAccountConfirm,name='userAccountConfirm'),
    path('managerPages/managerAccountModify',managerAccountModify,name='managerAccountModify'),
    path('managerPages/modalAccountModifyPOST',modalAccountModifyPOST,name='modalAccountModifyPOST'),
    path('managerPages/getAccountModifyHistory',getAccountModifyHistory,name='getAccountModifyHistory'),
    path('like_change',like_change,name='like_change'),
    path('putStars',putStars,name='putStars'),
    path('checkRegDD', checkRegDD, name='checkRegDD'),

    # 推薦索引
    path('recommendIndexHome', recommendIndexHome, name='recommendIndexHome'),
    path('', login_required(home), name='home'),
]

# Use include() to add paths from the catalog application
from django.conf.urls import include

urlpatterns += [
    path('pointManage/', include('pointManage.urls')),
    path('managerPages/', include('managerPage.urls')),
    path('personalInfoPage/', include('personalInfoPage.urls')),
    path('courseReplay/', include('courseReplay.urls')),
]

server/userlogin/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser  # 匯入 AbstractUser 類
from django.contrib.auth.hashers import make_password
from django.contrib.sessions.models import Session

# Create your models here.
class Server(models.Model):
    class Meta:
        permissions = (
            ("can_see_register", "允許產生註冊網址"),
            ("seeManagerMenuButton", "允許操作選單的管理按鈕"),
            ("seeManagerAccountManagerPage", "允許操作帳號管理"),
            ("seeManagerAuditAccountPage", "允許操作審核管理"),
            ("seeManagerPointPage", "允許操作點數管理"),
            ("seeManagerArticlePage", "允許操作文章管理"),
            ("seeManagerArticleReportPage", "允許操作文章回報管理"),
            ("seeManagerStatisticPage", "允許操作統計管理"),
            ("seeManagerRewardReportPage", "允許操作獎賞管理"),
            ("seeManagerBlackListPage", "允許操作黑名單"),
            ("ALLAuditManager", "全教室審查管理權限"),
            ("CYPManager", "台北教室管理權限"),
            ("CYLManager", "中壢教室管理權限"),
            ("CYSManager", "新竹教室管理權限"),
            ("CYZManager", "台中教室管理權限"),
            ("CYJManager", "嘉義教室管理權限"),
            ("CYN2Manager", "永康245管理權限"),
            ("CYN1Manager", "永康135管理權限"),
            ("CYMManager", "良美教室管理權限"),
            ("CYKManager", "高雄教室管理權限"),
            ("CYDManager", "屏東教室管理權限"),
            ("CYWManager", "花蓮教室管理權限"),
            ("CYTManager", "台東教室管理權限"),
            ("CYHManager", "澎湖教室管理權限"),
            ("can_Change_DataPermission", "允許管理帳號的檔案權限等級"),
            ("can_Change_JobTitle", "允需管理帳號的職位"),
            ("can_Change_class", "允許管理帳號的教室"),
            # ("can_Change_Point", "允許直接修改帳號的點數"),
            ("NutrilliteArticleManage", "營養檔案管理權限"),
            ("ArtistryArticleManage", "美容檔案管理權限"),
            ("TechArticleManage", "科技檔案管理權限"),
            ("AmwayQueenArticleManage", "金鍋檔案管理權限"),
            ("OtherArticleManage", "其他檔案管理權限"),
            ("ChainyenArticleManage", "總部檔案管理權限"),
            ("SpeechArticleManage", "演講廳檔案管理權限"),
            ("articlePointManage", "檔案點數修改權限"),
            ("articleReport", "文章回報"),
            ("rewardReport", "獎賞回報"),
            # ("articleReportManage", "文章回報管理"),
            ("can_freeze_account", "允許管理帳號凍結"),
            ("classRoomAccount", "教室法人帳號"),
            ("seeCourseReplay", "允許觀看課程重播"),
        )


class UserAccountInfo(AbstractUser):
    """
    繼承 AbstractUser
    新增欄位：phone、addr
    """
    user = models.CharField(max_length=20, verbose_name='姓名')

    gender = models.CharField(max_length=4, verbose_name='性別')
    phone = models.CharField(max_length=50, verbose_name='電話')
    dataPermissionsLevel = models.IntegerField(verbose_name='資料權限等級')
    last_session_key = models.CharField(blank=True, null=True, max_length=40)

    class Meta:
        verbose_name = "帳號管理"
        verbose_name_plural = "帳號管理"

    def set_session_key(self, key):
        if self.last_session_key and not self.last_session_key == key:
            session_key = Session.objects.filter(session_key=self.last_session_key)
            if session_key:
                session_key.get().delete()
        self.last_session_key = key
        self.save()


class UserAccountAmwayInfo(models.Model):
    UserAccountInfo = models.ForeignKey("UserAccountInfo", on_delete=models.CASCADE, verbose_name='帳號')
    amwayNumber = models.CharField(max_length=20,verbose_name='會員編號')
    amwayAward = models.ForeignKey("amwayAwardInfo", on_delete=models.CASCADE, verbose_name='獎銜')
    amwayDD = models.ForeignKey("registerDDandDimInfo", verbose_name='白金', on_delete=models.PROTECT)

    # amwayDiamond = models.CharField(max_length=20, verbose_name='鑽石')
    class Meta:
        verbose_name = "帳號管理-安麗相關"
        verbose_name_plural = "帳號管理-安麗相關"


class UserAccountChainYenInfo(models.Model):
    UserAccountInfo = models.ForeignKey("UserAccountInfo", on_delete=models.CASCADE, verbose_name='帳號')
    jobTitle = models.ForeignKey("chainYenJobTitleInfo", on_delete=models.CASCADE, verbose_name='職務')
    classRoom = models.ForeignKey("chainYenClassInfo", on_delete=models.CASCADE, verbose_name='教室')
    # babysitter = models.CharField(max_length=20, verbose_name='保母')

    accountStatus = models.CharField(max_length=4, verbose_name='狀態')  # 停權
    freezeDate = models.DateTimeField(verbose_name='停權到期日', null=True,blank=True)
    point = models.IntegerField(verbose_name='點數')

    EM = models.BooleanField(verbose_name='愛馬')

    class Meta:
        verbose_name = "帳號管理-群雁相關"
        verbose_name_plural = "帳號管理-群雁相關"


class amwayAwardInfo(models.Model):
    rank = models.IntegerField()
    amwayAward = models.CharField(max_length=20, verbose_name='獎銜')

    class Meta:
        verbose_name = "獎銜資料表"
        verbose_name_plural = "獎銜資料表"

    def __str__(self):
        return self.amwayAward


class chainYenJobTitleInfo(models.Model):
    rank = models.IntegerField()
    jobTitle = models.CharField(max_length=20, verbose_name='職位')

    class Meta:
        verbose_name = "職位資料表"
        verbose_name_plural = "職位資料表"

    def __str__(self):
        return self.jobTitle


class chainYenClassInfo(models.Model):
    rank = models.IntegerField()
    ClassRoomName = models.CharField(max_length=20, verbose_name='教室名稱')
    ClassRoomCode = models.CharField(max_length=20, verbose_name='教室代碼')

    class Meta:
        verbose_name = "教室資料表"
        verbose_name_plural = "教室資料表"

    def __str__(self):
        return self.ClassRoomName


class registerDDandDimInfo(models.Model):
    amwayAward = models.ForeignKey("amwayAwardInfo", verbose_name='獎銜', on_delete=models.PROTECT)  # 只有白金跟鑽石
    amwayNumber = models.CharField(max_length=20,verbose_name='會員編號')
    amwayDiamond = models.CharField(max_length=20, verbose_name='上手鑽石')
    main = models.CharField(max_length=20, verbose_name='主直銷權')
    sec = models.CharField(max_length=20, verbose_name='次直銷權', null=True,blank=True)

    class Meta:
        verbose_name = "白金列表"
        verbose_name_plural = "白金列表"

    def __str__(self):
        return self.main


class TempUserAccountInfo(models.Model):
    """
    繼承 AbstractUser
    新增欄位：phone、addr
    """
    username = models.CharField(max_length=20, verbose_name='帳號')
    user = models.CharField(max_length=20, verbose_name='姓名')

    gender = models.CharField(max_length=4, verbose_name='性別')
    phone = models.CharField(max_length=50, verbose_name='電話')
    password = models.CharField(max_length=128, verbose_name='密碼')
    email = models.CharField(max_length=254, verbose_name='信箱')
    dataPermissionsLevel = models.IntegerField(verbose_name='資料權限等級')
    auditStatus = models.CharField(max_length=20, verbose_name='審核狀態')  # 審核中 #已寄信

    class Meta:
        verbose_name = "註冊中帳號列表"
        verbose_name_plural = "註冊中帳號列表"
    def __str__(self):
        return self.username

class TempUserAccountAmwayInfo(models.Model):
    UserAccountInfo = models.ForeignKey("TempUserAccountInfo", on_delete=models.CASCADE,verbose_name='帳號')
    amwayNumber = models.CharField(max_length=20,verbose_name='會員編號')
    amwayAward = models.ForeignKey("amwayAwardInfo", on_delete=models.CASCADE, verbose_name='獎銜')
    amwayDD = models.ForeignKey("registerDDandDimInfo", verbose_name='白金', on_delete=models.PROTECT)
    # amwayDiamond = models.CharField(max_length=20, verbose_name='鑽石')
    class Meta:
        verbose_name = "註冊中帳號列表-安麗相關"
        verbose_name_plural = "註冊中帳號列表-安麗相關"

class TempUserAccountChainYenInfo(models.Model):
    UserAccountInfo = models.ForeignKey("TempUserAccountInfo", on_delete=models.CASCADE,verbose_name='帳號')
    jobTitle = models.ForeignKey("chainYenJobTitleInfo", on_delete=models.CASCADE, verbose_name='職務')
    classRoom = models.ForeignKey("chainYenClassInfo", on_delete=models.CASCADE, verbose_name='教室')
    # babysitter = models.CharField(max_length=20, verbose_name='保母')

    accountStatus = models.CharField(max_length=4, verbose_name='狀態')  # 停權
    freezeDate = models.DateTimeField(verbose_name='停權到期日', null=True,blank=True)
    point = models.IntegerField(verbose_name='點數')

    EM = models.BooleanField(verbose_name='愛馬')

    class Meta:
        verbose_name = "註冊中帳號列表-群雁相關"
        verbose_name_plural = "註冊中帳號列表-群雁相關"

class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user_name = models.CharField(max_length=20, verbose_name='帳號')
    c_time = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.user.name + ":   " + self.code

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "註冊確認碼"
        verbose_name_plural = "註冊確認碼"

class ConfirmStringForPWD(models.Model):
    code = models.CharField(max_length=256)
    user_name = models.CharField(max_length=20, verbose_name='帳號')
    c_time = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.user.name + ":   " + self.code

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "忘記密碼確認碼"
        verbose_name_plural = "忘記密碼確認碼"

# 修改紀錄
class AccountModifyHistory(models.Model):
    UserAccountInfo = models.ForeignKey("userlogin.UserAccountInfo", on_delete=models.CASCADE, verbose_name="被變更者")
    modifier = models.CharField(verbose_name="變更者", max_length=100)
    recordDate = models.DateTimeField(verbose_name='修改日期')
    modifyFielddName = models.CharField(verbose_name="變更欄位", max_length=100)
    originFieldData = models.CharField(verbose_name="原始值", max_length=255)
    RevisedData = models.CharField(verbose_name="變更後值", max_length=255)

    class Meta:
        verbose_name = "帳號更動歷史紀錄"
        verbose_name_plural = "帳號更動歷史紀錄"


class loginHistory(models.Model):
    user= models.ForeignKey(UserAccountInfo, on_delete=models.CASCADE,verbose_name="登入帳號")
    date= models.DateTimeField(auto_now_add= True,verbose_name="登入時間")
    ip = models.CharField(verbose_name="ip", max_length=100)

    class Meta:
        verbose_name = "登入紀錄"
        verbose_name_plural = "登入紀錄"

    def __str__(self):
        return str(self.user) + ': ' + str(self.date)

server/templates/personalInfoPages/changePasswordOptionResult.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>ChainYen System</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		{% load static %}
		<link href="{%static 'favicon.ico' %}" rel="shortcut icon">
	</head>
	<body class="is-preload" style="background-size: Cover;background:url('{%static 'images/login底圖.png' %}');">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					{% include 'baseHeader.html' %}

				<!-- Menu -->
					{% include 'baseMenu.html' %}
				<h2  style="margin-left: 100px;color:black">{{ message }}</h2>

                <script>
                    window.setTimeout("window.location='/'",5000);
                </script>
			</div>

		<!-- Scripts -->

			<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	</body>
</html>

server/templates/personalInfoPages/changePasswordPage.html
<!DOCTYPE html>
<!-- saved from url=(0040)http://127.0.0.1:8080/accounts/register/ -->
<html lang="en">
<head>
    <title>ChainYen System</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		{% load static %}
        <link href="{%static 'favicon.ico' %}" rel="shortcut icon">
		
</head>
<body class="is-preload" style="background-size: Cover;background:url('{%static 'images/login底圖.png' %}');">

<!-- Wrapper -->
			<div id="wrapper" >

				<!-- Header -->
                {% include 'baseHeader.html' %}

                <!-- Menu -->
                {% include 'baseMenu.html' %}


				<!-- Banner -->
					<section id="" class="">
						<div class="inner">
							<header class="major">

								<h2>密碼修改</h2>
							</header>
<!--							<div class="content">-->
                                <form action="{% url 'changePasswordOption' %}" method="post">{% csrf_token %}
                                    <div name="step1">

                                    <p>
                                        <label for="id_password1">舊密碼:</label>
                                        <input style="color:black;" type="password" name="id_password_old" autocomplete="new-password"
                                                                                    required="" id="id_password_old"
                                        >
                                        <span class="helptext"></span>
                                    </p>

                                    <p>
                                        <label for="id_password1">新密碼:</label>
                                        <input type="password" name="id_password1" autocomplete="new-password"
                                                                                    required="" id="id_password1" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,20}$"
                                               oninput="setCustomValidity('');" oninvalid="setCustomValidity('請輸入正確的密碼格式:請包含英文大小寫及數字且為8到20碼');"
                                               placeholder="請包含英文大小寫及數字且為8到20碼"
                                        >
                                        <span class="helptext"></span>
                                    </p>


                                    <p>
                                        <label for="id_password2">再次確認新密碼:</label>
                                        <input type="password" name="id_password2"
                                               autocomplete="new-password" required=""
                                               id="id_password2"
                                               oninput="setCustomValidity('');"
                                               onchange="if(document.getElementById('id_password1').value != document.getElementById('id_password2').value){setCustomValidity('兩次密碼不吻合');}"
                                        >
                                    </p>
                                    {% if passwordConfirm %}
                                        <p style="color: red;">兩次輸入的密碼不一致</p>
                                    {% endif %}
                                    </div>

                                <input id="confirmBtn" type="submit" value="確定修改">
                            </form>
                            <input id="goback" type ="button" onclick="history.back()" value="回到上一頁">



						</div>
					</section>

			</div>

		<!-- Scripts -->

</body>
</html>



<style type="text/css">
    label {
     color: #BFFFFF        /* 透過 CSS 重新定義元素的排列方式 */
    }
    h2 {color:black;}
    #id_password_old,#id_password2,#id_password1 {
        color:black;
        /*border: 1px solid black;*/
        background-color: rgba(244, 244, 255, 0.4);
    }
    #confirmBtn {
        color:black;
        border: 1px solid black;
    }
    label{
      color: black;
    }
    #goback {
        color:black;
        border: 1px solid black;
    }


</style>

server/templates/personalInfoPages/personalInfoHomePageSearchBar.html
<div class="row justify-content-start">
    <div class="col">
        <header class="major">
            <h2 style="color:black;">個人資料</h2>
        </header>
    </div>
    </div>
<div class="row justify-content-start">
    
    <div class="col align-items-center">
        <form action="{% url 'personalInfoHomePage' selectTag='全部' %}" method="post">{% csrf_token %}
            <input class="primary medium rounded " {% if selectPage == '瀏覽曾兌換資料' %} style="background-color:#c2c9d1" {% endif %} type="submit" value="瀏覽曾兌換資料">
        </form>
    </div>
    <div class="col">
        <form action="{% url 'changePasswordPage' %}" method="post">{% csrf_token %}
            <input class="primary medium rounded " type="submit" value="修改個人密碼">
        </form>
    </div>
    <div class="col">
        <form action="{% url 'personalInfoPointPage' %}" method="get">{% csrf_token %}
            <input class="primary medium rounded " {% if selectPage == '管理個人點數' %} style="background-color:#c2c9d1" {% endif %} type="submit" value="管理個人點數">
        </form>
    </div>
    {% if perms.userlogin.rewardReport %}
        <form action="{% url 'personalRewardReport' %}" method="get">{% csrf_token %}
            <input class="primary rounded" {% if selectPage == '獎賞回報' %} style="background-color:#c2c9d1" {% endif %} type="submit" value="獎賞回報">
        </form>
    {% endif %}
</div>

server/templates/personalInfoPages/personalInfoPointPage.html
<!DOCTYPE HTML>
<!--
    Forty by HTML5 UP
    html5up.net | @ajlkn
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<html>

<head>
    <title>ChainYen System</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    {% load static %}
</head>

<body class="is-preload" style="background-size: Cover;background:url('{%static 'images/login底圖.png' %}');">


    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        {% include 'baseHeader.html' %}

        <!-- Menu -->
        {% include 'baseMenu.html' %}

        <!-- Main -->

        <div id="main" class="alt">
            <section id="one" class="spotlights">
                <div class="inner">
                    {% include 'personalInfoPages/personalInfoHomePageSearchBar.html' %}
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-link active btn-warning" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                                role="tab" aria-controls="nav-home" aria-selected="true">
                                點數紀錄
                            </a>
                            {% if myTeam %}
                            <a class="nav-link btn-warning ml-1" id="nav-profile-tab" data-toggle="tab"
                                href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">
                                轉讓點數
                            </a>
                            {% endif %}
                            <!--
                            <a class="nav-link btn-warning ml-1" id="nav-contact-tab" data-toggle="tab"
                                href="#nav-contact" role="tab" aria-controls="nav-contact"
                                aria-selected="false">
                                兌換點數
                            </a>
                            -->
                            
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                            aria-labelledby="nav-home-tab">
                            <br>
                            {% include 'personalInfoPages/personalInfoPointPageHistory.html' %}
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            {% include 'personalInfoPages/personalInfoPointPageTransfer.html' %}
                        </div>
                        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            {% include 'personalInfoPages/personalInfoPointPageExchange.html' %}
                        </div>
                    </div>
                </div>
        </div>

        </section>
        {% if pageisNotNull %}
        <div class="dataTables_paginate paging_simple_numbers pull-right inner">
            <ul class="pagination ">
                {{ pagination.page_html|safe }}
            </ul>
        </div>
        {% endif %}
    </div>

    </div>


    <!-- Scripts -->
    <script src="{% static 'assets/js/personPointManager.js' %}"></script>
</body>

</html>

server/templates/personalInfoPages/personalInfoPointPageExchange.html
<div>開發中,敬請期待!</div>

server/templates/personalInfoPages/personalInfoPointPageHistory.html
<table id="myHistoryTable" class="display table table-light table-bordered" style="border:dark;width:100%; white-space: nowrap;">
    <thead class="thead-dark">
        <tr>
            <th>變更者</th>
            <th>修改日期</th>
            <th>增/扣/轉讓</th>
            <th>原因</th>
            <th>剩餘點數</th>
        </tr>
    </thead>
</table>
<style>
    .dataTables_filter input {
        background-color: white;
        color: black;
        border-radius: 5px;
    }
    label{
        color:black;
    }

    .dataTables_info{
        color:black;
    }

    th, td {border-width:10px}
</style>

server/templates/personalInfoPages/personalInfoPointPageTransfer.html
<div class="row">
    <div class="text-dark">您目前的點數: <span class="selfPoint" id="{{userAccountInfo.username}}_point">{{userAccountInfo.useraccountchainyeninfo_set.first.point}}</span></div>
</div>
<table id="myTransferTable" class="display table table-light table-bordered" style="border:dark;width:100%; white-space: nowrap;">
    <thead class="thead-dark">
        <tr>
            <th>直銷商</th>
            <th>直銷編號</th>
            <th>目前點數</th>
            <th>轉讓 1 點</th>
            <th>轉讓 10 點</th>
            <th>自訂轉讓點數</th>
        </tr>
    </thead>
</table>

<style>
    .modal-content {
        background-color: #2a2f4a;
    }

    .dataTables_filter input {
        background-color: white;
        color: black;
        border-radius: 5px;
    }
    label{
        color:black;
    }

    .dataTables_info{
        color:black;
    }

    th, td {border-width:10px}
</style>

  